version: '3.6'
services:

  db:
    image: postgres:10.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=catalog

  adminer:
    image: adminer
    ports:
      - 8080:8080

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db

  migration:
    build: .
    command: python manage.py migrate
    links:
      - db
    depends_on:
      - db